[package]
authors = ["Jacob LeCoq (BigBanana) <lecoqjacob@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name    = "yendor_utility"
version = "0.1.0"

[dependencies]
bevy   = { workspace = true, version = "0.9" }
fxhash = "0.2"
ulid   = { version = "1" }
